---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://victoriametrics.github.io/helm-charts/
    chart: victoria-metrics-single
    targetRevision: 0.23.0
    helm:
      values: |
        # No configuramos TLS ni Ingress en operator
        server:
          ingress:
            enabled: false
          tls:
            enabled: false
          scrape:
            enabled: true
          vmServiceScrape:
            enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: victoria-metrics-operator-webhook
      jqPathExpressions: ['.webhooks[]?.clientConfig.caBundle']
